### ISSUE TITLE
Po odhlášení uživatele je možné s aplikací pracovat

### ISSUE THREAD

**Issue by daliboris** [LIBCAS/DL4DH-Kramerius-plus#54]
### Postup

- přihlásím se jako uživatel
- zobrazím seznam žádostí obohacení
- z nabídky uživatele vyberu `Odhlásit`

### Výsledek

- seznam žádostí obohacení zůstane zobrazen
- klikáním na odkazy se dostanu na další stránky, dokonce až na detail publikace, kterou můžu zveřejnit

**Comment by bodnarIQ** [comment]
Opraveno

**Comment by daliboris** [comment]
Opraveno.
