### ISSUE TITLE
Chyba 500 při zobrazení detailu úlohy obohacení

### ISSUE THREAD

**Issue by daliboris** [LIBCAS/DL4DH-Kramerius-plus#55]
### Postup

- zadám obohacení publikací z kolekce spiritualistických textů (pomocí REST API)
- v seznamu žádostí o obohacení (`/enrichment/`) vyberu poslední kolekci

 ### Výsledek

- zobrazí se prázdná stránka
- v ladicích nástrojích je následující výstup:

 ```json
{
  "status" : 500,
  "error" : "Internal Server Error",
  "path" : "GET: /api/enrichment/2a27259b-ce07-44d2-aebd-80af9d4dc78e",
  "timestamp" : "2023-01-25T17:50:00.702409Z",
  "exception" : "org.hibernate.HibernateException",
  "message" : "Unable to access lob stream",
  "cause" : "org.postgresql.util.PSQLException: Large Objects may not be used in auto-commit mode."
}
```

**Comment by bodnarIQ** [comment]
Chyba bola spojena s vytahovanim chybovych hlasok z DB, opraveno
